package Pojo;
// Generated 18/05/2017 12:10:35 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;

/**
 * GimAuditoria generated by hbm2java
 */
public class GimAuditoria  implements java.io.Serializable {


     private BigDecimal audId;
     private Serializable audFechaproceso;
     private String audProceso;
     private BigDecimal usuId;

    public GimAuditoria() {
    }

	
    public GimAuditoria(BigDecimal audId, String audProceso, BigDecimal usuId) {
        this.audId = audId;
        this.audProceso = audProceso;
        this.usuId = usuId;
    }
    public GimAuditoria(BigDecimal audId, Serializable audFechaproceso, String audProceso, BigDecimal usuId) {
       this.audId = audId;
       this.audFechaproceso = audFechaproceso;
       this.audProceso = audProceso;
       this.usuId = usuId;
    }
   
    public BigDecimal getAudId() {
        return this.audId;
    }
    
    public void setAudId(BigDecimal audId) {
        this.audId = audId;
    }
    public Serializable getAudFechaproceso() {
        return this.audFechaproceso;
    }
    
    public void setAudFechaproceso(Serializable audFechaproceso) {
        this.audFechaproceso = audFechaproceso;
    }
    public String getAudProceso() {
        return this.audProceso;
    }
    
    public void setAudProceso(String audProceso) {
        this.audProceso = audProceso;
    }
    public BigDecimal getUsuId() {
        return this.usuId;
    }
    
    public void setUsuId(BigDecimal usuId) {
        this.usuId = usuId;
    }




}


