package Pojo;
// Generated 28/04/2017 10:08:51 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * GimGrupos generated by hbm2java
 */
public class GimGrupos  implements java.io.Serializable {


     private BigDecimal gruId;
     private String gruDescripcion;
     private Set gimParametroses = new HashSet(0);

    public GimGrupos() {
    }

	
    public GimGrupos(BigDecimal gruId, String gruDescripcion) {
        this.gruId = gruId;
        this.gruDescripcion = gruDescripcion;
    }
    public GimGrupos(BigDecimal gruId, String gruDescripcion, Set gimParametroses) {
       this.gruId = gruId;
       this.gruDescripcion = gruDescripcion;
       this.gimParametroses = gimParametroses;
    }
   
    public BigDecimal getGruId() {
        return this.gruId;
    }
    
    public void setGruId(BigDecimal gruId) {
        this.gruId = gruId;
    }
    public String getGruDescripcion() {
        return this.gruDescripcion;
    }
    
    public void setGruDescripcion(String gruDescripcion) {
        this.gruDescripcion = gruDescripcion;
    }
    public Set getGimParametroses() {
        return this.gimParametroses;
    }
    
    public void setGimParametroses(Set gimParametroses) {
        this.gimParametroses = gimParametroses;
    }




}


