package Pojo;
// Generated 18/05/2017 12:10:35 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * GimInsCli generated by hbm2java
 */
public class GimInsCli  implements java.io.Serializable {


     private GimInsCliId id;
     private GimCliente gimCliente;
     private GimInstructor gimInstructor;
     private Date inscliFechaInicial;
     private Date inscliFechaFinal;
     private BigDecimal inscliEstado;

    public GimInsCli() {
    }

	
    public GimInsCli(GimInsCliId id, GimCliente gimCliente, GimInstructor gimInstructor, Date inscliFechaInicial, BigDecimal inscliEstado) {
        this.id = id;
        this.gimCliente = gimCliente;
        this.gimInstructor = gimInstructor;
        this.inscliFechaInicial = inscliFechaInicial;
        this.inscliEstado = inscliEstado;
    }
    public GimInsCli(GimInsCliId id, GimCliente gimCliente, GimInstructor gimInstructor, Date inscliFechaInicial, Date inscliFechaFinal, BigDecimal inscliEstado) {
       this.id = id;
       this.gimCliente = gimCliente;
       this.gimInstructor = gimInstructor;
       this.inscliFechaInicial = inscliFechaInicial;
       this.inscliFechaFinal = inscliFechaFinal;
       this.inscliEstado = inscliEstado;
    }
   
    public GimInsCliId getId() {
        return this.id;
    }
    
    public void setId(GimInsCliId id) {
        this.id = id;
    }
    public GimCliente getGimCliente() {
        return this.gimCliente;
    }
    
    public void setGimCliente(GimCliente gimCliente) {
        this.gimCliente = gimCliente;
    }
    public GimInstructor getGimInstructor() {
        return this.gimInstructor;
    }
    
    public void setGimInstructor(GimInstructor gimInstructor) {
        this.gimInstructor = gimInstructor;
    }
    public Date getInscliFechaInicial() {
        return this.inscliFechaInicial;
    }
    
    public void setInscliFechaInicial(Date inscliFechaInicial) {
        this.inscliFechaInicial = inscliFechaInicial;
    }
    public Date getInscliFechaFinal() {
        return this.inscliFechaFinal;
    }
    
    public void setInscliFechaFinal(Date inscliFechaFinal) {
        this.inscliFechaFinal = inscliFechaFinal;
    }
    public BigDecimal getInscliEstado() {
        return this.inscliEstado;
    }
    
    public void setInscliEstado(BigDecimal inscliEstado) {
        this.inscliEstado = inscliEstado;
    }




}


