package Pojo;
// Generated 18/05/2017 12:10:35 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * GimInstructor generated by hbm2java
 */
public class GimInstructor  implements java.io.Serializable {


     private BigDecimal instId;
     private GimPersona gimPersona;
     private Date instFechaingreso;
     private Date instFechadesvinculacion;
     private BigDecimal instEspecialidad;
     private BigDecimal instNivelestudio;
     private Date instFechaproceso;
     private BigDecimal instEstado;
     private BigDecimal instNivelnutricion;
     private String instCodigo;
     private Set gimInsClis = new HashSet(0);

    public GimInstructor() {
    }

	
    public GimInstructor(BigDecimal instId, GimPersona gimPersona, BigDecimal instNivelestudio, BigDecimal instEstado, BigDecimal instNivelnutricion, String instCodigo) {
        this.instId = instId;
        this.gimPersona = gimPersona;
        this.instNivelestudio = instNivelestudio;
        this.instEstado = instEstado;
        this.instNivelnutricion = instNivelnutricion;
        this.instCodigo = instCodigo;
    }
    public GimInstructor(BigDecimal instId, GimPersona gimPersona, Date instFechaingreso, Date instFechadesvinculacion, BigDecimal instEspecialidad, BigDecimal instNivelestudio, Date instFechaproceso, BigDecimal instEstado, BigDecimal instNivelnutricion, String instCodigo) {
       this.instId = instId;
       this.gimPersona = gimPersona;
       this.instFechaingreso = instFechaingreso;
       this.instFechadesvinculacion = instFechadesvinculacion;
       this.instEspecialidad = instEspecialidad;
       this.instNivelestudio = instNivelestudio;
       this.instFechaproceso = instFechaproceso;
       this.instEstado = instEstado;
       this.instNivelnutricion = instNivelnutricion;
       this.instCodigo = instCodigo;
    }
   
    public BigDecimal getInstId() {
        return this.instId;
    }
    
    public void setInstId(BigDecimal instId) {
        this.instId = instId;
    }
    public GimPersona getGimPersona() {
        return this.gimPersona;
    }
    
    public void setGimPersona(GimPersona gimPersona) {
        this.gimPersona = gimPersona;
    }
    public Date getInstFechaingreso() {
        return this.instFechaingreso;
    }
    
    public void setInstFechaingreso(Date instFechaingreso) {
        this.instFechaingreso = instFechaingreso;
    }
    public Date getInstFechadesvinculacion() {
        return this.instFechadesvinculacion;
    }
    
    public void setInstFechadesvinculacion(Date instFechadesvinculacion) {
        this.instFechadesvinculacion = instFechadesvinculacion;
    }
    public BigDecimal getInstEspecialidad() {
        return this.instEspecialidad;
    }
    
    public void setInstEspecialidad(BigDecimal instEspecialidad) {
        this.instEspecialidad = instEspecialidad;
    }
    public BigDecimal getInstNivelestudio() {
        return this.instNivelestudio;
    }
    
    public void setInstNivelestudio(BigDecimal instNivelestudio) {
        this.instNivelestudio = instNivelestudio;
    }
    public Date getInstFechaproceso() {
        return this.instFechaproceso;
    }
    
    public void setInstFechaproceso(Date instFechaproceso) {
        this.instFechaproceso = instFechaproceso;
    }
    public BigDecimal getInstEstado() {
        return this.instEstado;
    }
    
    public void setInstEstado(BigDecimal instEstado) {
        this.instEstado = instEstado;
    }
    public BigDecimal getInstNivelnutricion() {
        return this.instNivelnutricion;
    }
    
    public void setInstNivelnutricion(BigDecimal instNivelnutricion) {
        this.instNivelnutricion = instNivelnutricion;
    }
    public String getInstCodigo() {
        return this.instCodigo;
    }
    
    public void setInstCodigo(String instCodigo) {
        this.instCodigo = instCodigo;
    }
    public Set getGimInsClis() {
        return this.gimInsClis;
    }
    
    public void setGimInsClis(Set gimInsClis) {
        this.gimInsClis = gimInsClis;
    }




}


