package Pojo;
// Generated 18/05/2017 12:10:35 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * GimInsCliId generated by hbm2java
 */
public class GimInsCliId  implements java.io.Serializable {


     private BigDecimal cliId;
     private BigDecimal instId;

    public GimInsCliId() {
    }

    public GimInsCliId(BigDecimal cliId, BigDecimal instId) {
       this.cliId = cliId;
       this.instId = instId;
    }
   
    public BigDecimal getCliId() {
        return this.cliId;
    }
    
    public void setCliId(BigDecimal cliId) {
        this.cliId = cliId;
    }
    public BigDecimal getInstId() {
        return this.instId;
    }
    
    public void setInstId(BigDecimal instId) {
        this.instId = instId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GimInsCliId) ) return false;
		 GimInsCliId castOther = ( GimInsCliId ) other; 
         
		 return ( (this.getCliId()==castOther.getCliId()) || ( this.getCliId()!=null && castOther.getCliId()!=null && this.getCliId().equals(castOther.getCliId()) ) )
 && ( (this.getInstId()==castOther.getInstId()) || ( this.getInstId()!=null && castOther.getInstId()!=null && this.getInstId().equals(castOther.getInstId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCliId() == null ? 0 : this.getCliId().hashCode() );
         result = 37 * result + ( getInstId() == null ? 0 : this.getInstId().hashCode() );
         return result;
   }   


}


