package Pojo;
// Generated 28/04/2017 10:08:51 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * GimMemUsu generated by hbm2java
 */
public class GimMemUsu  implements java.io.Serializable {


     private GimMemUsuId id;
     private Date memUsuFechaproceso;
     private Date memUsuFechainicial;
     private Date memUsuFechafinal;

    public GimMemUsu() {
    }

	
    public GimMemUsu(GimMemUsuId id, Date memUsuFechafinal) {
        this.id = id;
        this.memUsuFechafinal = memUsuFechafinal;
    }
    public GimMemUsu(GimMemUsuId id, Date memUsuFechaproceso, Date memUsuFechainicial, Date memUsuFechafinal) {
       this.id = id;
       this.memUsuFechaproceso = memUsuFechaproceso;
       this.memUsuFechainicial = memUsuFechainicial;
       this.memUsuFechafinal = memUsuFechafinal;
    }
   
    public GimMemUsuId getId() {
        return this.id;
    }
    
    public void setId(GimMemUsuId id) {
        this.id = id;
    }
    public Date getMemUsuFechaproceso() {
        return this.memUsuFechaproceso;
    }
    
    public void setMemUsuFechaproceso(Date memUsuFechaproceso) {
        this.memUsuFechaproceso = memUsuFechaproceso;
    }
    public Date getMemUsuFechainicial() {
        return this.memUsuFechainicial;
    }
    
    public void setMemUsuFechainicial(Date memUsuFechainicial) {
        this.memUsuFechainicial = memUsuFechainicial;
    }
    public Date getMemUsuFechafinal() {
        return this.memUsuFechafinal;
    }
    
    public void setMemUsuFechafinal(Date memUsuFechafinal) {
        this.memUsuFechafinal = memUsuFechafinal;
    }




}


