package Pojo;
// Generated 28/04/2017 10:08:51 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * GimMembresia generated by hbm2java
 */
public class GimMembresia  implements java.io.Serializable {


     private BigDecimal memId;
     private BigDecimal memTipo;
     private String memDescripcion;

    public GimMembresia() {
    }

    public GimMembresia(BigDecimal memId, BigDecimal memTipo, String memDescripcion) {
       this.memId = memId;
       this.memTipo = memTipo;
       this.memDescripcion = memDescripcion;
    }
   
    public BigDecimal getMemId() {
        return this.memId;
    }
    
    public void setMemId(BigDecimal memId) {
        this.memId = memId;
    }
    public BigDecimal getMemTipo() {
        return this.memTipo;
    }
    
    public void setMemTipo(BigDecimal memTipo) {
        this.memTipo = memTipo;
    }
    public String getMemDescripcion() {
        return this.memDescripcion;
    }
    
    public void setMemDescripcion(String memDescripcion) {
        this.memDescripcion = memDescripcion;
    }




}


