package Pojo;
// Generated 16/05/2017 10:24:10 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * GimModulo generated by hbm2java
 */
public class GimModulo  implements java.io.Serializable {


     private BigDecimal modId;
     private String modNombre;
     private Date modFechainicial;
     private Date modFechafinal;
     private Date modFechaproceso;
     private BigDecimal modEstado;
     private String icono;
     private Set gimRecursos = new HashSet(0);

    public GimModulo() {
    }

	
    public GimModulo(BigDecimal modId, String modNombre, Date modFechainicial, Date modFechaproceso, BigDecimal modEstado) {
        this.modId = modId;
        this.modNombre = modNombre;
        this.modFechainicial = modFechainicial;
        this.modFechaproceso = modFechaproceso;
        this.modEstado = modEstado;
    }
    public GimModulo(BigDecimal modId, String modNombre, Date modFechainicial, Date modFechafinal, Date modFechaproceso, BigDecimal modEstado, String icono, Set gimRecursos) {
       this.modId = modId;
       this.modNombre = modNombre;
       this.modFechainicial = modFechainicial;
       this.modFechafinal = modFechafinal;
       this.modFechaproceso = modFechaproceso;
       this.modEstado = modEstado;
       this.icono = icono;
       this.gimRecursos = gimRecursos;
    }
   
    public BigDecimal getModId() {
        return this.modId;
    }
    
    public void setModId(BigDecimal modId) {
        this.modId = modId;
    }
    public String getModNombre() {
        return this.modNombre;
    }
    
    public void setModNombre(String modNombre) {
        this.modNombre = modNombre;
    }
    public Date getModFechainicial() {
        return this.modFechainicial;
    }
    
    public void setModFechainicial(Date modFechainicial) {
        this.modFechainicial = modFechainicial;
    }
    public Date getModFechafinal() {
        return this.modFechafinal;
    }
    
    public void setModFechafinal(Date modFechafinal) {
        this.modFechafinal = modFechafinal;
    }
    public Date getModFechaproceso() {
        return this.modFechaproceso;
    }
    
    public void setModFechaproceso(Date modFechaproceso) {
        this.modFechaproceso = modFechaproceso;
    }
    public BigDecimal getModEstado() {
        return this.modEstado;
    }
    
    public void setModEstado(BigDecimal modEstado) {
        this.modEstado = modEstado;
    }
    public String getIcono() {
        return this.icono;
    }
    
    public void setIcono(String icono) {
        this.icono = icono;
    }
    public Set getGimRecursos() {
        return this.gimRecursos;
    }
    
    public void setGimRecursos(Set gimRecursos) {
        this.gimRecursos = gimRecursos;
    }




}


