package Pojo;
// Generated 18/05/2017 12:10:35 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * GimPlanClienteId generated by hbm2java
 */
public class GimPlanClienteId  implements java.io.Serializable {


     private BigDecimal planId;
     private BigDecimal cliId;

    public GimPlanClienteId() {
    }

    public GimPlanClienteId(BigDecimal planId, BigDecimal cliId) {
       this.planId = planId;
       this.cliId = cliId;
    }
   
    public BigDecimal getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(BigDecimal planId) {
        this.planId = planId;
    }
    public BigDecimal getCliId() {
        return this.cliId;
    }
    
    public void setCliId(BigDecimal cliId) {
        this.cliId = cliId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GimPlanClienteId) ) return false;
		 GimPlanClienteId castOther = ( GimPlanClienteId ) other; 
         
		 return ( (this.getPlanId()==castOther.getPlanId()) || ( this.getPlanId()!=null && castOther.getPlanId()!=null && this.getPlanId().equals(castOther.getPlanId()) ) )
 && ( (this.getCliId()==castOther.getCliId()) || ( this.getCliId()!=null && castOther.getCliId()!=null && this.getCliId().equals(castOther.getCliId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPlanId() == null ? 0 : this.getPlanId().hashCode() );
         result = 37 * result + ( getCliId() == null ? 0 : this.getCliId().hashCode() );
         return result;
   }   


}


