package Pojo;
// Generated 16/05/2017 10:24:10 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * GimPerfilrecurso generated by hbm2java
 */
public class GimPerfilrecurso  implements java.io.Serializable {


     private GimPerfilrecursoId id;
     private Date perfrecFechainicial;
     private Date perfrecFechafinal;
     private Date perfrecFechaproceso;

    public GimPerfilrecurso() {
    }

	
    public GimPerfilrecurso(GimPerfilrecursoId id, Date perfrecFechainicial, Date perfrecFechaproceso) {
        this.id = id;
        this.perfrecFechainicial = perfrecFechainicial;
        this.perfrecFechaproceso = perfrecFechaproceso;
    }
    public GimPerfilrecurso(GimPerfilrecursoId id, Date perfrecFechainicial, Date perfrecFechafinal, Date perfrecFechaproceso) {
       this.id = id;
       this.perfrecFechainicial = perfrecFechainicial;
       this.perfrecFechafinal = perfrecFechafinal;
       this.perfrecFechaproceso = perfrecFechaproceso;
    }
   
    public GimPerfilrecursoId getId() {
        return this.id;
    }
    
    public void setId(GimPerfilrecursoId id) {
        this.id = id;
    }
    public Date getPerfrecFechainicial() {
        return this.perfrecFechainicial;
    }
    
    public void setPerfrecFechainicial(Date perfrecFechainicial) {
        this.perfrecFechainicial = perfrecFechainicial;
    }
    public Date getPerfrecFechafinal() {
        return this.perfrecFechafinal;
    }
    
    public void setPerfrecFechafinal(Date perfrecFechafinal) {
        this.perfrecFechafinal = perfrecFechafinal;
    }
    public Date getPerfrecFechaproceso() {
        return this.perfrecFechaproceso;
    }
    
    public void setPerfrecFechaproceso(Date perfrecFechaproceso) {
        this.perfrecFechaproceso = perfrecFechaproceso;
    }




}


