package Pojo;
// Generated 28/04/2017 10:08:51 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * GimPlanTrabajo generated by hbm2java
 */
public class GimPlanTrabajo  implements java.io.Serializable {


     private BigDecimal planId;
     private GimUsuario gimUsuario;
     private String planDescripcion;
     private String planNombre;
     private BigDecimal planTipoEjercicio;
     private Date planFechaproceso;
     private BigDecimal planEstado;
     private String planCodigo;
     private Set gimPlanRuts = new HashSet(0);

    public GimPlanTrabajo() {
    }

	
    public GimPlanTrabajo(BigDecimal planId, GimUsuario gimUsuario, String planDescripcion, String planNombre, BigDecimal planTipoEjercicio, BigDecimal planEstado, String planCodigo) {
        this.planId = planId;
        this.gimUsuario = gimUsuario;
        this.planDescripcion = planDescripcion;
        this.planNombre = planNombre;
        this.planTipoEjercicio = planTipoEjercicio;
        this.planEstado = planEstado;
        this.planCodigo = planCodigo;
    }
    public GimPlanTrabajo(BigDecimal planId, GimUsuario gimUsuario, String planDescripcion, String planNombre, BigDecimal planTipoEjercicio, Date planFechaproceso, BigDecimal planEstado, String planCodigo) {
       this.planId = planId;
       this.gimUsuario = gimUsuario;
       this.planDescripcion = planDescripcion;
       this.planNombre = planNombre;
       this.planTipoEjercicio = planTipoEjercicio;
       this.planFechaproceso = planFechaproceso;
       this.planEstado = planEstado;
       this.planCodigo = planCodigo;
    }
   
    public BigDecimal getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(BigDecimal planId) {
        this.planId = planId;
    }
    public GimUsuario getGimUsuario() {
        return this.gimUsuario;
    }
    
    public void setGimUsuario(GimUsuario gimUsuario) {
        this.gimUsuario = gimUsuario;
    }
    public String getPlanDescripcion() {
        return this.planDescripcion;
    }
    
    public void setPlanDescripcion(String planDescripcion) {
        this.planDescripcion = planDescripcion;
    }
    public String getPlanNombre() {
        return this.planNombre;
    }
    
    public void setPlanNombre(String planNombre) {
        this.planNombre = planNombre;
    }
    public BigDecimal getPlanTipoEjercicio() {
        return this.planTipoEjercicio;
    }
    
    public void setPlanTipoEjercicio(BigDecimal planTipoEjercicio) {
        this.planTipoEjercicio = planTipoEjercicio;
    }
    public Date getPlanFechaproceso() {
        return this.planFechaproceso;
    }
    
    public void setPlanFechaproceso(Date planFechaproceso) {
        this.planFechaproceso = planFechaproceso;
    }
    public BigDecimal getPlanEstado() {
        return this.planEstado;
    }
    
    public void setPlanEstado(BigDecimal planEstado) {
        this.planEstado = planEstado;
    }
    public String getPlanCodigo() {
        return this.planCodigo;
    }
    
    public void setPlanCodigo(String planCodigo) {
        this.planCodigo = planCodigo;
    }
    public Set getGimPlanRuts() {
        return this.gimPlanRuts;
    }
    
    public void setGimPlanRuts(Set gimPlanRuts) {
        this.gimPlanRuts = gimPlanRuts;
    }




}


