package Pojo;
// Generated 18/05/2017 12:10:35 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * GimPlanCliente generated by hbm2java
 */
public class GimPlanCliente  implements java.io.Serializable {


     private GimPlanClienteId id;
     private GimCliente gimCliente;
     private GimPlanTrabajo gimPlanTrabajo;
     private BigDecimal plclEstado;
     private Date plclFechaInicial;
     private Date plclFechaFinal;
     private Date plclFechaProceso;

    public GimPlanCliente() {
    }

	
    public GimPlanCliente(GimPlanClienteId id, GimCliente gimCliente, GimPlanTrabajo gimPlanTrabajo, BigDecimal plclEstado, Date plclFechaInicial) {
        this.id = id;
        this.gimCliente = gimCliente;
        this.gimPlanTrabajo = gimPlanTrabajo;
        this.plclEstado = plclEstado;
        this.plclFechaInicial = plclFechaInicial;
    }
    public GimPlanCliente(GimPlanClienteId id, GimCliente gimCliente, GimPlanTrabajo gimPlanTrabajo, BigDecimal plclEstado, Date plclFechaInicial, Date plclFechaFinal, Date plclFechaProceso) {
       this.id = id;
       this.gimCliente = gimCliente;
       this.gimPlanTrabajo = gimPlanTrabajo;
       this.plclEstado = plclEstado;
       this.plclFechaInicial = plclFechaInicial;
       this.plclFechaFinal = plclFechaFinal;
       this.plclFechaProceso = plclFechaProceso;
    }
   
    public GimPlanClienteId getId() {
        return this.id;
    }
    
    public void setId(GimPlanClienteId id) {
        this.id = id;
    }
    public GimCliente getGimCliente() {
        return this.gimCliente;
    }
    
    public void setGimCliente(GimCliente gimCliente) {
        this.gimCliente = gimCliente;
    }
    public GimPlanTrabajo getGimPlanTrabajo() {
        return this.gimPlanTrabajo;
    }
    
    public void setGimPlanTrabajo(GimPlanTrabajo gimPlanTrabajo) {
        this.gimPlanTrabajo = gimPlanTrabajo;
    }
    public BigDecimal getPlclEstado() {
        return this.plclEstado;
    }
    
    public void setPlclEstado(BigDecimal plclEstado) {
        this.plclEstado = plclEstado;
    }
    public Date getPlclFechaInicial() {
        return this.plclFechaInicial;
    }
    
    public void setPlclFechaInicial(Date plclFechaInicial) {
        this.plclFechaInicial = plclFechaInicial;
    }
    public Date getPlclFechaFinal() {
        return this.plclFechaFinal;
    }
    
    public void setPlclFechaFinal(Date plclFechaFinal) {
        this.plclFechaFinal = plclFechaFinal;
    }
    public Date getPlclFechaProceso() {
        return this.plclFechaProceso;
    }
    
    public void setPlclFechaProceso(Date plclFechaProceso) {
        this.plclFechaProceso = plclFechaProceso;
    }




}


