package Pojo;
// Generated 28/04/2017 10:08:51 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * GimPlanRutId generated by hbm2java
 */
public class GimPlanRutId  implements java.io.Serializable {


     private BigDecimal planId;
     private BigDecimal rutId;

    public GimPlanRutId() {
    }

    public GimPlanRutId(BigDecimal planId, BigDecimal rutId) {
       this.planId = planId;
       this.rutId = rutId;
    }
   
    public BigDecimal getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(BigDecimal planId) {
        this.planId = planId;
    }
    public BigDecimal getRutId() {
        return this.rutId;
    }
    
    public void setRutId(BigDecimal rutId) {
        this.rutId = rutId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GimPlanRutId) ) return false;
		 GimPlanRutId castOther = ( GimPlanRutId ) other; 
         
		 return ( (this.getPlanId()==castOther.getPlanId()) || ( this.getPlanId()!=null && castOther.getPlanId()!=null && this.getPlanId().equals(castOther.getPlanId()) ) )
 && ( (this.getRutId()==castOther.getRutId()) || ( this.getRutId()!=null && castOther.getRutId()!=null && this.getRutId().equals(castOther.getRutId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPlanId() == null ? 0 : this.getPlanId().hashCode() );
         result = 37 * result + ( getRutId() == null ? 0 : this.getRutId().hashCode() );
         return result;
   }   


}


