package Pojo;
// Generated 16/05/2017 10:24:10 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * GimPerfilrecursoId generated by hbm2java
 */
public class GimPerfilrecursoId  implements java.io.Serializable {


     private BigDecimal perfId;
     private BigDecimal recId;

    public GimPerfilrecursoId() {
    }

    public GimPerfilrecursoId(BigDecimal perfId, BigDecimal recId) {
       this.perfId = perfId;
       this.recId = recId;
    }
   
    public BigDecimal getPerfId() {
        return this.perfId;
    }
    
    public void setPerfId(BigDecimal perfId) {
        this.perfId = perfId;
    }
    public BigDecimal getRecId() {
        return this.recId;
    }
    
    public void setRecId(BigDecimal recId) {
        this.recId = recId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GimPerfilrecursoId) ) return false;
		 GimPerfilrecursoId castOther = ( GimPerfilrecursoId ) other; 
         
		 return ( (this.getPerfId()==castOther.getPerfId()) || ( this.getPerfId()!=null && castOther.getPerfId()!=null && this.getPerfId().equals(castOther.getPerfId()) ) )
 && ( (this.getRecId()==castOther.getRecId()) || ( this.getRecId()!=null && castOther.getRecId()!=null && this.getRecId().equals(castOther.getRecId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPerfId() == null ? 0 : this.getPerfId().hashCode() );
         result = 37 * result + ( getRecId() == null ? 0 : this.getRecId().hashCode() );
         return result;
   }   


}


