package Pojo;
// Generated 18/05/2017 12:10:35 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * GimPlanRut generated by hbm2java
 */
public class GimPlanRut  implements java.io.Serializable {


     private GimPlanRutId id;
     private GimPlanTrabajo gimPlanTrabajo;
     private GimRutina gimRutina;
     private Date planRutFechaproceso;

    public GimPlanRut() {
    }

	
    public GimPlanRut(GimPlanRutId id, GimPlanTrabajo gimPlanTrabajo, GimRutina gimRutina) {
        this.id = id;
        this.gimPlanTrabajo = gimPlanTrabajo;
        this.gimRutina = gimRutina;
    }
    public GimPlanRut(GimPlanRutId id, GimPlanTrabajo gimPlanTrabajo, GimRutina gimRutina, Date planRutFechaproceso) {
       this.id = id;
       this.gimPlanTrabajo = gimPlanTrabajo;
       this.gimRutina = gimRutina;
       this.planRutFechaproceso = planRutFechaproceso;
    }
   
    public GimPlanRutId getId() {
        return this.id;
    }
    
    public void setId(GimPlanRutId id) {
        this.id = id;
    }
    public GimPlanTrabajo getGimPlanTrabajo() {
        return this.gimPlanTrabajo;
    }
    
    public void setGimPlanTrabajo(GimPlanTrabajo gimPlanTrabajo) {
        this.gimPlanTrabajo = gimPlanTrabajo;
    }
    public GimRutina getGimRutina() {
        return this.gimRutina;
    }
    
    public void setGimRutina(GimRutina gimRutina) {
        this.gimRutina = gimRutina;
    }
    public Date getPlanRutFechaproceso() {
        return this.planRutFechaproceso;
    }
    
    public void setPlanRutFechaproceso(Date planRutFechaproceso) {
        this.planRutFechaproceso = planRutFechaproceso;
    }




}


