package Pojo;
// Generated 16/05/2017 10:24:10 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * GimPersona generated by hbm2java
 */
public class GimPersona  implements java.io.Serializable {


     private BigDecimal persId;
     private String persNombre1;
     private String persNombre2;
     private String persApellido1;
     private String persApellido2;
     private BigDecimal persTipodocumento;
     private Date persFechanacimiento;
     private BigDecimal persLugarnacimiento;
     private BigDecimal persGruposanguineo;
     private String persRh;
     private BigDecimal persSexo;
     private Date persFechafinal;
     private Date persFechainicial;
     private BigDecimal persEstado;
     private String persNumerodocumento;
     private String persEmail;
     private Set gimUsuarios = new HashSet(0);
     private Set gimClientes = new HashSet(0);
     private Set gimInstructors = new HashSet(0);
     private Set gimTelefonos = new HashSet(0);
     private Set gimDireccions = new HashSet(0);

    public GimPersona() {
    }

	
    public GimPersona(BigDecimal persId, String persNombre1, String persApellido1, String persApellido2, BigDecimal persTipodocumento, BigDecimal persGruposanguineo, String persRh, BigDecimal persSexo, BigDecimal persEstado, String persNumerodocumento, String persEmail) {
        this.persId = persId;
        this.persNombre1 = persNombre1;
        this.persApellido1 = persApellido1;
        this.persApellido2 = persApellido2;
        this.persTipodocumento = persTipodocumento;
        this.persGruposanguineo = persGruposanguineo;
        this.persRh = persRh;
        this.persSexo = persSexo;
        this.persEstado = persEstado;
        this.persNumerodocumento = persNumerodocumento;
        this.persEmail = persEmail;
    }
    public GimPersona(BigDecimal persId, String persNombre1, String persNombre2, String persApellido1, String persApellido2, BigDecimal persTipodocumento, Date persFechanacimiento, BigDecimal persLugarnacimiento, BigDecimal persGruposanguineo, String persRh, BigDecimal persSexo, Date persFechafinal, Date persFechainicial, BigDecimal persEstado, String persNumerodocumento, String persEmail) {
       this.persId = persId;
       this.persNombre1 = persNombre1;
       this.persNombre2 = persNombre2;
       this.persApellido1 = persApellido1;
       this.persApellido2 = persApellido2;
       this.persTipodocumento = persTipodocumento;
       this.persFechanacimiento = persFechanacimiento;
       this.persLugarnacimiento = persLugarnacimiento;
       this.persGruposanguineo = persGruposanguineo;
       this.persRh = persRh;
       this.persSexo = persSexo;
       this.persFechafinal = persFechafinal;
       this.persFechainicial = persFechainicial;
       this.persEstado = persEstado;
       this.persNumerodocumento = persNumerodocumento;
       this.persEmail = persEmail;
    }
   
    public BigDecimal getPersId() {
        return this.persId;
    }
    
    public void setPersId(BigDecimal persId) {
        this.persId = persId;
    }
    public String getPersNombre1() {
        return this.persNombre1;
    }
    
    public void setPersNombre1(String persNombre1) {
        this.persNombre1 = persNombre1;
    }
    public String getPersNombre2() {
        return this.persNombre2;
    }
    
    public void setPersNombre2(String persNombre2) {
        this.persNombre2 = persNombre2;
    }
    public String getPersApellido1() {
        return this.persApellido1;
    }
    
    public void setPersApellido1(String persApellido1) {
        this.persApellido1 = persApellido1;
    }
    public String getPersApellido2() {
        return this.persApellido2;
    }
    
    public void setPersApellido2(String persApellido2) {
        this.persApellido2 = persApellido2;
    }
    public BigDecimal getPersTipodocumento() {
        return this.persTipodocumento;
    }
    
    public void setPersTipodocumento(BigDecimal persTipodocumento) {
        this.persTipodocumento = persTipodocumento;
    }
    public Date getPersFechanacimiento() {
        return this.persFechanacimiento;
    }
    
    public void setPersFechanacimiento(Date persFechanacimiento) {
        this.persFechanacimiento = persFechanacimiento;
    }
    public BigDecimal getPersLugarnacimiento() {
        return this.persLugarnacimiento;
    }
    
    public void setPersLugarnacimiento(BigDecimal persLugarnacimiento) {
        this.persLugarnacimiento = persLugarnacimiento;
    }
    public BigDecimal getPersGruposanguineo() {
        return this.persGruposanguineo;
    }
    
    public void setPersGruposanguineo(BigDecimal persGruposanguineo) {
        this.persGruposanguineo = persGruposanguineo;
    }
    public String getPersRh() {
        return this.persRh;
    }
    
    public void setPersRh(String persRh) {
        this.persRh = persRh;
    }
    public BigDecimal getPersSexo() {
        return this.persSexo;
    }
    
    public void setPersSexo(BigDecimal persSexo) {
        this.persSexo = persSexo;
    }
    public Date getPersFechafinal() {
        return this.persFechafinal;
    }
    
    public void setPersFechafinal(Date persFechafinal) {
        this.persFechafinal = persFechafinal;
    }
    public Date getPersFechainicial() {
        return this.persFechainicial;
    }
    
    public void setPersFechainicial(Date persFechainicial) {
        this.persFechainicial = persFechainicial;
    }
    public BigDecimal getPersEstado() {
        return this.persEstado;
    }
    
    public void setPersEstado(BigDecimal persEstado) {
        this.persEstado = persEstado;
    }
    public String getPersNumerodocumento() {
        return this.persNumerodocumento;
    }
    
    public void setPersNumerodocumento(String persNumerodocumento) {
        this.persNumerodocumento = persNumerodocumento;
    }
    public String getPersEmail() {
        return this.persEmail;
    }
    
    public void setPersEmail(String persEmail) {
        this.persEmail = persEmail;
    }
    public Set getGimUsuarios() {
        return this.gimUsuarios;
    }
    
    public void setGimUsuarios(Set gimUsuarios) {
        this.gimUsuarios = gimUsuarios;
    }
    public Set getGimClientes() {
        return this.gimClientes;
    }
    
    public void setGimClientes(Set gimClientes) {
        this.gimClientes = gimClientes;
    }
    public Set getGimInstructors() {
        return this.gimInstructors;
    }
    
    public void setGimInstructors(Set gimInstructors) {
        this.gimInstructors = gimInstructors;
    }
    public Set getGimTelefonos() {
        return this.gimTelefonos;
    }
    
    public void setGimTelefonos(Set gimTelefonos) {
        this.gimTelefonos = gimTelefonos;
    }
    public Set getGimDireccions() {
        return this.gimDireccions;
    }
    
    public void setGimDireccions(Set gimDireccions) {
        this.gimDireccions = gimDireccions;
    }




}


