package Pojo;
// Generated 16/05/2017 10:24:10 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * GimParametros generated by hbm2java
 */
public class GimParametros  implements java.io.Serializable {


     private BigDecimal parId;
     private GimGrupos gimGrupos;
     private BigDecimal parCodigo;
     private String parNombrecorto;
     private String parNombre;

    public GimParametros() {
    }

	
    public GimParametros(BigDecimal parId, GimGrupos gimGrupos, BigDecimal parCodigo, String parNombre) {
        this.parId = parId;
        this.gimGrupos = gimGrupos;
        this.parCodigo = parCodigo;
        this.parNombre = parNombre;
    }
    public GimParametros(BigDecimal parId, GimGrupos gimGrupos, BigDecimal parCodigo, String parNombrecorto, String parNombre) {
       this.parId = parId;
       this.gimGrupos = gimGrupos;
       this.parCodigo = parCodigo;
       this.parNombrecorto = parNombrecorto;
       this.parNombre = parNombre;
    }
   
    public BigDecimal getParId() {
        return this.parId;
    }
    
    public void setParId(BigDecimal parId) {
        this.parId = parId;
    }
    public GimGrupos getGimGrupos() {
        return this.gimGrupos;
    }
    
    public void setGimGrupos(GimGrupos gimGrupos) {
        this.gimGrupos = gimGrupos;
    }
    public BigDecimal getParCodigo() {
        return this.parCodigo;
    }
    
    public void setParCodigo(BigDecimal parCodigo) {
        this.parCodigo = parCodigo;
    }
    public String getParNombrecorto() {
        return this.parNombrecorto;
    }
    
    public void setParNombrecorto(String parNombrecorto) {
        this.parNombrecorto = parNombrecorto;
    }
    public String getParNombre() {
        return this.parNombre;
    }
    
    public void setParNombre(String parNombre) {
        this.parNombre = parNombre;
    }




}


