package Pojo;
// Generated 18/05/2017 12:10:35 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * GimRecurso generated by hbm2java
 */
public class GimRecurso  implements java.io.Serializable {


     private BigDecimal recId;
     private GimModulo gimModulo;
     private String recNombre;
     private String recDescripcion;
     private Date recFechainicial;
     private Date recFechafinal;
     private String recCarpeta;
     private Date recFechaproceso;
     private BigDecimal recEstado;
     private BigDecimal recTipo;

    public GimRecurso() {
    }

	
    public GimRecurso(BigDecimal recId, GimModulo gimModulo, String recNombre, Date recFechainicial, String recCarpeta, BigDecimal recEstado) {
        this.recId = recId;
        this.gimModulo = gimModulo;
        this.recNombre = recNombre;
        this.recFechainicial = recFechainicial;
        this.recCarpeta = recCarpeta;
        this.recEstado = recEstado;
    }
    public GimRecurso(BigDecimal recId, GimModulo gimModulo, String recNombre, String recDescripcion, Date recFechainicial, Date recFechafinal, String recCarpeta, Date recFechaproceso, BigDecimal recEstado, BigDecimal recTipo) {
       this.recId = recId;
       this.gimModulo = gimModulo;
       this.recNombre = recNombre;
       this.recDescripcion = recDescripcion;
       this.recFechainicial = recFechainicial;
       this.recFechafinal = recFechafinal;
       this.recCarpeta = recCarpeta;
       this.recFechaproceso = recFechaproceso;
       this.recEstado = recEstado;
       this.recTipo = recTipo;
    }
   
    public BigDecimal getRecId() {
        return this.recId;
    }
    
    public void setRecId(BigDecimal recId) {
        this.recId = recId;
    }
    public GimModulo getGimModulo() {
        return this.gimModulo;
    }
    
    public void setGimModulo(GimModulo gimModulo) {
        this.gimModulo = gimModulo;
    }
    public String getRecNombre() {
        return this.recNombre;
    }
    
    public void setRecNombre(String recNombre) {
        this.recNombre = recNombre;
    }
    public String getRecDescripcion() {
        return this.recDescripcion;
    }
    
    public void setRecDescripcion(String recDescripcion) {
        this.recDescripcion = recDescripcion;
    }
    public Date getRecFechainicial() {
        return this.recFechainicial;
    }
    
    public void setRecFechainicial(Date recFechainicial) {
        this.recFechainicial = recFechainicial;
    }
    public Date getRecFechafinal() {
        return this.recFechafinal;
    }
    
    public void setRecFechafinal(Date recFechafinal) {
        this.recFechafinal = recFechafinal;
    }
    public String getRecCarpeta() {
        return this.recCarpeta;
    }
    
    public void setRecCarpeta(String recCarpeta) {
        this.recCarpeta = recCarpeta;
    }
    public Date getRecFechaproceso() {
        return this.recFechaproceso;
    }
    
    public void setRecFechaproceso(Date recFechaproceso) {
        this.recFechaproceso = recFechaproceso;
    }
    public BigDecimal getRecEstado() {
        return this.recEstado;
    }
    
    public void setRecEstado(BigDecimal recEstado) {
        this.recEstado = recEstado;
    }
    public BigDecimal getRecTipo() {
        return this.recTipo;
    }
    
    public void setRecTipo(BigDecimal recTipo) {
        this.recTipo = recTipo;
    }




}


