package Pojo;
// Generated 16/05/2017 10:24:10 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * GimRutObj generated by hbm2java
 */
public class GimRutObj  implements java.io.Serializable {


     private GimRutObjId id;
     private GimObjetos gimObjetos;
     private GimRutina gimRutina;
     private Date rutObjFechaproceso;

    public GimRutObj() {
    }

	
    public GimRutObj(GimRutObjId id, GimObjetos gimObjetos, GimRutina gimRutina) {
        this.id = id;
        this.gimObjetos = gimObjetos;
        this.gimRutina = gimRutina;
    }
    public GimRutObj(GimRutObjId id, GimObjetos gimObjetos, GimRutina gimRutina, Date rutObjFechaproceso) {
       this.id = id;
       this.gimObjetos = gimObjetos;
       this.gimRutina = gimRutina;
       this.rutObjFechaproceso = rutObjFechaproceso;
    }
   
    public GimRutObjId getId() {
        return this.id;
    }
    
    public void setId(GimRutObjId id) {
        this.id = id;
    }
    public GimObjetos getGimObjetos() {
        return this.gimObjetos;
    }
    
    public void setGimObjetos(GimObjetos gimObjetos) {
        this.gimObjetos = gimObjetos;
    }
    public GimRutina getGimRutina() {
        return this.gimRutina;
    }
    
    public void setGimRutina(GimRutina gimRutina) {
        this.gimRutina = gimRutina;
    }
    public Date getRutObjFechaproceso() {
        return this.rutObjFechaproceso;
    }
    
    public void setRutObjFechaproceso(Date rutObjFechaproceso) {
        this.rutObjFechaproceso = rutObjFechaproceso;
    }




}


