package Pojo;
// Generated 28/04/2017 10:08:51 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * GimTelefono generated by hbm2java
 */
public class GimTelefono  implements java.io.Serializable {


     private BigDecimal telId;
     private GimPersona gimPersona;
     private String telTelefono;
     private String telCelular;
     private Date telFechaproceso;
     private BigDecimal telEstado;

    public GimTelefono() {
    }

	
    public GimTelefono(BigDecimal telId, GimPersona gimPersona, BigDecimal telEstado) {
        this.telId = telId;
        this.gimPersona = gimPersona;
        this.telEstado = telEstado;
    }
    public GimTelefono(BigDecimal telId, GimPersona gimPersona, String telTelefono, String telCelular, Date telFechaproceso, BigDecimal telEstado) {
       this.telId = telId;
       this.gimPersona = gimPersona;
       this.telTelefono = telTelefono;
       this.telCelular = telCelular;
       this.telFechaproceso = telFechaproceso;
       this.telEstado = telEstado;
    }
   
    public BigDecimal getTelId() {
        return this.telId;
    }
    
    public void setTelId(BigDecimal telId) {
        this.telId = telId;
    }
    public GimPersona getGimPersona() {
        return this.gimPersona;
    }
    
    public void setGimPersona(GimPersona gimPersona) {
        this.gimPersona = gimPersona;
    }
    public String getTelTelefono() {
        return this.telTelefono;
    }
    
    public void setTelTelefono(String telTelefono) {
        this.telTelefono = telTelefono;
    }
    public String getTelCelular() {
        return this.telCelular;
    }
    
    public void setTelCelular(String telCelular) {
        this.telCelular = telCelular;
    }
    public Date getTelFechaproceso() {
        return this.telFechaproceso;
    }
    
    public void setTelFechaproceso(Date telFechaproceso) {
        this.telFechaproceso = telFechaproceso;
    }
    public BigDecimal getTelEstado() {
        return this.telEstado;
    }
    
    public void setTelEstado(BigDecimal telEstado) {
        this.telEstado = telEstado;
    }




}


