package Pojo;
// Generated 16/05/2017 10:24:10 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * GimValoracionMaestro generated by hbm2java
 */
public class GimValoracionMaestro  implements java.io.Serializable {


     private BigDecimal valId;
     private BigDecimal cliId;
     private BigDecimal instId;
     private Date valFechaproceso;

    public GimValoracionMaestro() {
    }

	
    public GimValoracionMaestro(BigDecimal valId, BigDecimal cliId, BigDecimal instId) {
        this.valId = valId;
        this.cliId = cliId;
        this.instId = instId;
    }
    public GimValoracionMaestro(BigDecimal valId, BigDecimal cliId, BigDecimal instId, Date valFechaproceso) {
       this.valId = valId;
       this.cliId = cliId;
       this.instId = instId;
       this.valFechaproceso = valFechaproceso;
    }
   
    public BigDecimal getValId() {
        return this.valId;
    }
    
    public void setValId(BigDecimal valId) {
        this.valId = valId;
    }
    public BigDecimal getCliId() {
        return this.cliId;
    }
    
    public void setCliId(BigDecimal cliId) {
        this.cliId = cliId;
    }
    public BigDecimal getInstId() {
        return this.instId;
    }
    
    public void setInstId(BigDecimal instId) {
        this.instId = instId;
    }
    public Date getValFechaproceso() {
        return this.valFechaproceso;
    }
    
    public void setValFechaproceso(Date valFechaproceso) {
        this.valFechaproceso = valFechaproceso;
    }




}


