package Pojo;
// Generated 16/05/2017 10:24:10 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * GimValoracionDetalle generated by hbm2java
 */
public class GimValoracionDetalle  implements java.io.Serializable {


     private BigDecimal detvalId;
     private BigDecimal detvalTrapecio;
     private BigDecimal detvalHombros;
     private BigDecimal detvalBicepderecho;
     private BigDecimal detvalBicepizquierdo;
     private BigDecimal detvalEspalda;
     private BigDecimal detvalDorsales;
     private BigDecimal detvalTricepderechoSup;
     private BigDecimal detvalTricepderechoInf;
     private BigDecimal detvalTricepizquierdoSup;
     private BigDecimal detvalTricepizquieroInf;
     private BigDecimal detvalPectorales;
     private BigDecimal detvalAbdomen;
     private BigDecimal detvalCaderas;
     private BigDecimal detvalCintura;
     private BigDecimal detvalGluteos;
     private BigDecimal detvalCuadricep;
     private BigDecimal detvalFemorales;
     private BigDecimal detvalAductores;
     private BigDecimal detvalPantorrillas;
     private BigDecimal detvalEstado;
     private BigDecimal valId;

    public GimValoracionDetalle() {
    }

	
    public GimValoracionDetalle(BigDecimal detvalId, BigDecimal detvalEstado, BigDecimal valId) {
        this.detvalId = detvalId;
        this.detvalEstado = detvalEstado;
        this.valId = valId;
    }
    public GimValoracionDetalle(BigDecimal detvalId, BigDecimal detvalTrapecio, BigDecimal detvalHombros, BigDecimal detvalBicepderecho, BigDecimal detvalBicepizquierdo, BigDecimal detvalEspalda, BigDecimal detvalDorsales, BigDecimal detvalTricepderechoSup, BigDecimal detvalTricepderechoInf, BigDecimal detvalTricepizquierdoSup, BigDecimal detvalTricepizquieroInf, BigDecimal detvalPectorales, BigDecimal detvalAbdomen, BigDecimal detvalCaderas, BigDecimal detvalCintura, BigDecimal detvalGluteos, BigDecimal detvalCuadricep, BigDecimal detvalFemorales, BigDecimal detvalAductores, BigDecimal detvalPantorrillas, BigDecimal detvalEstado, BigDecimal valId) {
       this.detvalId = detvalId;
       this.detvalTrapecio = detvalTrapecio;
       this.detvalHombros = detvalHombros;
       this.detvalBicepderecho = detvalBicepderecho;
       this.detvalBicepizquierdo = detvalBicepizquierdo;
       this.detvalEspalda = detvalEspalda;
       this.detvalDorsales = detvalDorsales;
       this.detvalTricepderechoSup = detvalTricepderechoSup;
       this.detvalTricepderechoInf = detvalTricepderechoInf;
       this.detvalTricepizquierdoSup = detvalTricepizquierdoSup;
       this.detvalTricepizquieroInf = detvalTricepizquieroInf;
       this.detvalPectorales = detvalPectorales;
       this.detvalAbdomen = detvalAbdomen;
       this.detvalCaderas = detvalCaderas;
       this.detvalCintura = detvalCintura;
       this.detvalGluteos = detvalGluteos;
       this.detvalCuadricep = detvalCuadricep;
       this.detvalFemorales = detvalFemorales;
       this.detvalAductores = detvalAductores;
       this.detvalPantorrillas = detvalPantorrillas;
       this.detvalEstado = detvalEstado;
       this.valId = valId;
    }
   
    public BigDecimal getDetvalId() {
        return this.detvalId;
    }
    
    public void setDetvalId(BigDecimal detvalId) {
        this.detvalId = detvalId;
    }
    public BigDecimal getDetvalTrapecio() {
        return this.detvalTrapecio;
    }
    
    public void setDetvalTrapecio(BigDecimal detvalTrapecio) {
        this.detvalTrapecio = detvalTrapecio;
    }
    public BigDecimal getDetvalHombros() {
        return this.detvalHombros;
    }
    
    public void setDetvalHombros(BigDecimal detvalHombros) {
        this.detvalHombros = detvalHombros;
    }
    public BigDecimal getDetvalBicepderecho() {
        return this.detvalBicepderecho;
    }
    
    public void setDetvalBicepderecho(BigDecimal detvalBicepderecho) {
        this.detvalBicepderecho = detvalBicepderecho;
    }
    public BigDecimal getDetvalBicepizquierdo() {
        return this.detvalBicepizquierdo;
    }
    
    public void setDetvalBicepizquierdo(BigDecimal detvalBicepizquierdo) {
        this.detvalBicepizquierdo = detvalBicepizquierdo;
    }
    public BigDecimal getDetvalEspalda() {
        return this.detvalEspalda;
    }
    
    public void setDetvalEspalda(BigDecimal detvalEspalda) {
        this.detvalEspalda = detvalEspalda;
    }
    public BigDecimal getDetvalDorsales() {
        return this.detvalDorsales;
    }
    
    public void setDetvalDorsales(BigDecimal detvalDorsales) {
        this.detvalDorsales = detvalDorsales;
    }
    public BigDecimal getDetvalTricepderechoSup() {
        return this.detvalTricepderechoSup;
    }
    
    public void setDetvalTricepderechoSup(BigDecimal detvalTricepderechoSup) {
        this.detvalTricepderechoSup = detvalTricepderechoSup;
    }
    public BigDecimal getDetvalTricepderechoInf() {
        return this.detvalTricepderechoInf;
    }
    
    public void setDetvalTricepderechoInf(BigDecimal detvalTricepderechoInf) {
        this.detvalTricepderechoInf = detvalTricepderechoInf;
    }
    public BigDecimal getDetvalTricepizquierdoSup() {
        return this.detvalTricepizquierdoSup;
    }
    
    public void setDetvalTricepizquierdoSup(BigDecimal detvalTricepizquierdoSup) {
        this.detvalTricepizquierdoSup = detvalTricepizquierdoSup;
    }
    public BigDecimal getDetvalTricepizquieroInf() {
        return this.detvalTricepizquieroInf;
    }
    
    public void setDetvalTricepizquieroInf(BigDecimal detvalTricepizquieroInf) {
        this.detvalTricepizquieroInf = detvalTricepizquieroInf;
    }
    public BigDecimal getDetvalPectorales() {
        return this.detvalPectorales;
    }
    
    public void setDetvalPectorales(BigDecimal detvalPectorales) {
        this.detvalPectorales = detvalPectorales;
    }
    public BigDecimal getDetvalAbdomen() {
        return this.detvalAbdomen;
    }
    
    public void setDetvalAbdomen(BigDecimal detvalAbdomen) {
        this.detvalAbdomen = detvalAbdomen;
    }
    public BigDecimal getDetvalCaderas() {
        return this.detvalCaderas;
    }
    
    public void setDetvalCaderas(BigDecimal detvalCaderas) {
        this.detvalCaderas = detvalCaderas;
    }
    public BigDecimal getDetvalCintura() {
        return this.detvalCintura;
    }
    
    public void setDetvalCintura(BigDecimal detvalCintura) {
        this.detvalCintura = detvalCintura;
    }
    public BigDecimal getDetvalGluteos() {
        return this.detvalGluteos;
    }
    
    public void setDetvalGluteos(BigDecimal detvalGluteos) {
        this.detvalGluteos = detvalGluteos;
    }
    public BigDecimal getDetvalCuadricep() {
        return this.detvalCuadricep;
    }
    
    public void setDetvalCuadricep(BigDecimal detvalCuadricep) {
        this.detvalCuadricep = detvalCuadricep;
    }
    public BigDecimal getDetvalFemorales() {
        return this.detvalFemorales;
    }
    
    public void setDetvalFemorales(BigDecimal detvalFemorales) {
        this.detvalFemorales = detvalFemorales;
    }
    public BigDecimal getDetvalAductores() {
        return this.detvalAductores;
    }
    
    public void setDetvalAductores(BigDecimal detvalAductores) {
        this.detvalAductores = detvalAductores;
    }
    public BigDecimal getDetvalPantorrillas() {
        return this.detvalPantorrillas;
    }
    
    public void setDetvalPantorrillas(BigDecimal detvalPantorrillas) {
        this.detvalPantorrillas = detvalPantorrillas;
    }
    public BigDecimal getDetvalEstado() {
        return this.detvalEstado;
    }
    
    public void setDetvalEstado(BigDecimal detvalEstado) {
        this.detvalEstado = detvalEstado;
    }
    public BigDecimal getValId() {
        return this.valId;
    }
    
    public void setValId(BigDecimal valId) {
        this.valId = valId;
    }




}


