package Pojo;
// Generated 16/05/2017 10:24:10 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * GimVideo generated by hbm2java
 */
public class GimVideo  implements java.io.Serializable {


     private BigDecimal vidId;
     private GimRutina gimRutina;
     private String vidDescripcion;
     private String vidDirArchivo;
     private Date vidFechaproceso;
     private BigDecimal vidEstado;

    public GimVideo() {
    }

	
    public GimVideo(BigDecimal vidId, GimRutina gimRutina, String vidDescripcion, String vidDirArchivo, BigDecimal vidEstado) {
        this.vidId = vidId;
        this.gimRutina = gimRutina;
        this.vidDescripcion = vidDescripcion;
        this.vidDirArchivo = vidDirArchivo;
        this.vidEstado = vidEstado;
    }
    public GimVideo(BigDecimal vidId, GimRutina gimRutina, String vidDescripcion, String vidDirArchivo, Date vidFechaproceso, BigDecimal vidEstado) {
       this.vidId = vidId;
       this.gimRutina = gimRutina;
       this.vidDescripcion = vidDescripcion;
       this.vidDirArchivo = vidDirArchivo;
       this.vidFechaproceso = vidFechaproceso;
       this.vidEstado = vidEstado;
    }
   
    public BigDecimal getVidId() {
        return this.vidId;
    }
    
    public void setVidId(BigDecimal vidId) {
        this.vidId = vidId;
    }
    public GimRutina getGimRutina() {
        return this.gimRutina;
    }
    
    public void setGimRutina(GimRutina gimRutina) {
        this.gimRutina = gimRutina;
    }
    public String getVidDescripcion() {
        return this.vidDescripcion;
    }
    
    public void setVidDescripcion(String vidDescripcion) {
        this.vidDescripcion = vidDescripcion;
    }
    public String getVidDirArchivo() {
        return this.vidDirArchivo;
    }
    
    public void setVidDirArchivo(String vidDirArchivo) {
        this.vidDirArchivo = vidDirArchivo;
    }
    public Date getVidFechaproceso() {
        return this.vidFechaproceso;
    }
    
    public void setVidFechaproceso(Date vidFechaproceso) {
        this.vidFechaproceso = vidFechaproceso;
    }
    public BigDecimal getVidEstado() {
        return this.vidEstado;
    }
    
    public void setVidEstado(BigDecimal vidEstado) {
        this.vidEstado = vidEstado;
    }




}


